### ISSUE TITLE
portmidi updates

### ISSUE THREAD

**Issue by rbdannenberg** [jh-midi/portmidi-sml#1]
Hi jh-midi,

I'm the creator of PortMidi. I was a bit surprised to find how many portmidi versions there are on Github. I've finally gotten around to making a number of updates that are mostly minor but long overdue.

I also decided it would be wise to host a copy of PortMidi on Github.

I went through every copy of PortMidi I could find, looking at 4583 files and running diff 7961 times, but who's counting? :-)

I picked up a few fixes from your collective works, although with this many files and changes, I'm sure I missed something.

Your repo appears to serve as a source of bindings for PolyML.  I hope you can add support for the new Pm_CreateVirtualInput() and Pm_CreateVirtualOutput() functions for Linux and macOS. Let me know any problems. If you tell me you updated and things work, I'll recommend your repo in rbdannenberg/portmidi/README.md. Note that you can also unbundle the bindings from the base portmidi implementation in C, and just refer to a particular version at rbdannenberg/portmidi. (Although rbdannenberg/portmidi has some old bindings for python, C#, and Java, I'm not planning to maintain or even keep them since they have been siphoned off and maintained in independent efforts. So I'm unbundling bindings from base code too.)

Thanks,
Roger

**Comment by jh-midi** [comment]
portmidi 2.0 is usable now at https://github.com/jh-midi/portmidi-sml2

**Comment by jh-midi** [comment]
now you can use portmidi 2.0 with PolyML

**Comment by jh-midi** [comment]
Hi Roger,
It seem my binding work well on Linux and implement Pm_CreateVirtualInput() and Pm_CreateVirtualOutput(), then I can open their input and output;
but on Mac Intel, opening output and input are not reliable .
I don't know how to implement the Macro TIME_PROC then perhaps this is the issue, I only use Memory.null.
I can only test on Mac Catalina Intel.
My implementation can't support M1 processor since I can't compile it.
Your help is welcome
JH

**Comment by rbdannenberg** [comment]
Hi JH,
    I'm not sure why virtual ports would be a problem on Mac, especially when they work on Linux. The test programs in C for virtual ports seem to work reliably. (Maybe you could see if they work under Catalina. See instructions in pm_test/README.txt.)
    TIME_PROC is only used in test programs to simplify the type checking. The default is Pt_Time which takes no parameters, but for generality, PortMidi calls (*midi->time_proc)(midi->time_info) which allows for a custom time function that needs some context. Fortunately, C allows the caller to pass a parameter that is unused by the callee, but you need to do some type casting to compile it, which is how TIME_PROC came about.
    If you pass NULL (0), PortMidi will initialize and use Pt_Time, but there are some test cases where I want to clearly initialize and start Pt_Time to get a time reference before calling PortMidi functions, so I explicitly call Pt_Start() and pass TIME_PROC rather than NULL. (I can't remember if this is really necessary or just for clarity.)
    Catalina is unsupported as of Nov, and I'm using Monterey (MacOS v12). Virtual ports are recent, so maybe never tested on Catalina. There are some CoreMIDI changes for MIDI 2.0, but I don't know if they are relevant (PortMidi has no MIDI 2.0 support). I think the best path would be to upgrade to Monterey if that's possible and test again. If tests fail under Monterey, at least I could try to replicate the problem here. (I could also be talked into upgrading to Ventura, the latest MacOS version.)
    I have an M2, but I think there's no point testing there if it does not work on Intel.
    Thanks,
    Roger

**Comment by jh-midi** [comment]
Hi Roger,
 virtual port play well on Catalina now.
thanks for your help,
JH
